#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
TF_DIR="${TF_DIR:-${REPO_ROOT}/terraform/aws}"
OUT_FILE="${OUT_FILE:-${TF_DIR}/terraform.tfvars}"
FORCE="${FORCE:-0}"

random_string() {
  length="${1:-32}"
  bytes=$(( (length + 1) / 2 ))
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$bytes" | cut -c "1-${length}"
  else
    od -An -N "$bytes" -tx1 /dev/urandom | tr -d ' \n' | cut -c "1-${length}"
  fi
}

detect_public_cidr() {
  if [ -n "${ALLOWED_SSH_CIDRS:-}" ]; then
    printf '%s\n' "$ALLOWED_SSH_CIDRS"
    return 0
  fi

  public_ip=""
  for url in \
    "https://checkip.amazonaws.com" \
    "https://api.ipify.org" \
    "https://ifconfig.me/ip"
  do
    public_ip="$(curl -fsSL --connect-timeout 3 --max-time 8 "$url" 2>/dev/null | tr -d '[:space:]' || true)"
    if printf '%s\n' "$public_ip" | grep -Eq '^[0-9]+(\.[0-9]+){3}$'; then
      printf '%s/32\n' "$public_ip"
      return 0
    fi
  done

  echo "failed to detect public IP; set ALLOWED_SSH_CIDRS explicitly" >&2
  echo "example: ALLOWED_SSH_CIDRS=\"203.0.113.10/32\" scripts/aws/generate_aws_tfvars.sh" >&2
  return 1
}

hcl_string() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

hcl_list() {
  values="$1"
  first=1
  printf '['
  old_ifs="$IFS"
  IFS=','
  for value in $values; do
    value="$(printf '%s' "$value" | xargs)"
    [ -n "$value" ] || continue
    if [ "$first" -eq 0 ]; then
      printf ', '
    fi
    printf '"%s"' "$(hcl_string "$value")"
    first=0
  done
  IFS="$old_ifs"
  printf ']'
}

if [ -f "$OUT_FILE" ] && [ "$FORCE" != "1" ]; then
  echo "refuse to overwrite existing file: ${OUT_FILE}" >&2
  echo "set FORCE=1 to regenerate it" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT_FILE")"

AWS_REGION="${AWS_REGION:-us-east-1}"
PROJECT_NAME="${PROJECT_NAME:-slayerfs-rustfs}"
DEPLOY_PROFILE="${DEPLOY_PROFILE:-dev}"
ALLOWED_SSH_CIDRS_VALUE="$(detect_public_cidr)"
EXPOSE_RUSTFS_CONSOLE="${EXPOSE_RUSTFS_CONSOLE:-false}"

CREATE_KEY_PAIR="${CREATE_KEY_PAIR:-true}"
KEY_NAME="${KEY_NAME:-}"
SSH_PRIVATE_KEY_PATH="${SSH_PRIVATE_KEY_PATH:-}"

case "$DEPLOY_PROFILE" in
  dev)
    DEFAULT_TIKV_INSTANCE_TYPE="m6i.xlarge"
    DEFAULT_RUSTFS_INSTANCE_TYPE="m6i.xlarge"
    DEFAULT_TIKV_DATA_VOLUME_SIZE_GB=512
    DEFAULT_RUSTFS_DATA_VOLUME_SIZE_GB=1024
    DEFAULT_DATA_VOLUME_IOPS=3000
    DEFAULT_DATA_VOLUME_THROUGHPUT=125
    DEFAULT_TARGET_TOTAL_FILES=1000000
    DEFAULT_FILES_PER_DIR=10000
    DEFAULT_TEST_THREADS=64
    ;;
  stress)
    DEFAULT_TIKV_INSTANCE_TYPE="m6i.2xlarge"
    DEFAULT_RUSTFS_INSTANCE_TYPE="m6i.2xlarge"
    DEFAULT_TIKV_DATA_VOLUME_SIZE_GB=2048
    DEFAULT_RUSTFS_DATA_VOLUME_SIZE_GB=4096
    DEFAULT_DATA_VOLUME_IOPS=12000
    DEFAULT_DATA_VOLUME_THROUGHPUT=500
    DEFAULT_TARGET_TOTAL_FILES=100000000
    DEFAULT_FILES_PER_DIR=100000
    DEFAULT_TEST_THREADS=256
    ;;
  *)
    echo "unknown DEPLOY_PROFILE=${DEPLOY_PROFILE}; use dev or stress" >&2
    exit 1
    ;;
esac

TIKV_INSTANCE_TYPE="${TIKV_INSTANCE_TYPE:-$DEFAULT_TIKV_INSTANCE_TYPE}"
RUSTFS_INSTANCE_TYPE="${RUSTFS_INSTANCE_TYPE:-$DEFAULT_RUSTFS_INSTANCE_TYPE}"
TIKV_DATA_VOLUME_SIZE_GB="${TIKV_DATA_VOLUME_SIZE_GB:-$DEFAULT_TIKV_DATA_VOLUME_SIZE_GB}"
RUSTFS_DATA_VOLUME_SIZE_GB="${RUSTFS_DATA_VOLUME_SIZE_GB:-$DEFAULT_RUSTFS_DATA_VOLUME_SIZE_GB}"
DATA_VOLUME_TYPE="${DATA_VOLUME_TYPE:-gp3}"
DATA_VOLUME_IOPS="${DATA_VOLUME_IOPS:-$DEFAULT_DATA_VOLUME_IOPS}"
DATA_VOLUME_THROUGHPUT="${DATA_VOLUME_THROUGHPUT:-$DEFAULT_DATA_VOLUME_THROUGHPUT}"

JUICEFS_VERSION="${JUICEFS_VERSION:-1.3.1}"
TIDB_VERSION="${TIDB_VERSION:-v8.5.6}"

RUSTFS_ACCESS_KEY="${RUSTFS_ACCESS_KEY:-rustfsadmin}"
RUSTFS_SECRET_KEY="${RUSTFS_SECRET_KEY:-$(random_string 32)}"
RUSTFS_BUCKET="${RUSTFS_BUCKET:-juicefs-prod}"
JFS_NAME="${JFS_NAME:-juicefs-prod}"

TARGET_TOTAL_FILES="${TARGET_TOTAL_FILES:-$DEFAULT_TARGET_TOTAL_FILES}"
FILES_PER_DIR="${FILES_PER_DIR:-$DEFAULT_FILES_PER_DIR}"
TEST_THREADS="${TEST_THREADS:-$DEFAULT_TEST_THREADS}"

cat >"$OUT_FILE" <<EOF
# Generated by scripts/aws/generate_aws_tfvars.sh.
# DEPLOY_PROFILE=${DEPLOY_PROFILE}
# Override values with environment variables, or edit this file before terraform apply.

aws_region = "$(hcl_string "$AWS_REGION")"
project_name = "$(hcl_string "$PROJECT_NAME")"

allowed_ssh_cidrs = $(hcl_list "$ALLOWED_SSH_CIDRS_VALUE")
expose_rustfs_console = ${EXPOSE_RUSTFS_CONSOLE}

create_key_pair = ${CREATE_KEY_PAIR}
key_name = "$(hcl_string "$KEY_NAME")"
ssh_private_key_path = "$(hcl_string "$SSH_PRIVATE_KEY_PATH")"

tikv_instance_type = "$(hcl_string "$TIKV_INSTANCE_TYPE")"
rustfs_instance_type = "$(hcl_string "$RUSTFS_INSTANCE_TYPE")"

tikv_data_volume_size_gb = ${TIKV_DATA_VOLUME_SIZE_GB}
rustfs_data_volume_size_gb = ${RUSTFS_DATA_VOLUME_SIZE_GB}
data_volume_type = "$(hcl_string "$DATA_VOLUME_TYPE")"
data_volume_iops = ${DATA_VOLUME_IOPS}
data_volume_throughput = ${DATA_VOLUME_THROUGHPUT}

juicefs_version = "$(hcl_string "$JUICEFS_VERSION")"
tidb_version = "$(hcl_string "$TIDB_VERSION")"

rustfs_access_key = "$(hcl_string "$RUSTFS_ACCESS_KEY")"
rustfs_secret_key = "$(hcl_string "$RUSTFS_SECRET_KEY")"
rustfs_bucket = "$(hcl_string "$RUSTFS_BUCKET")"
jfs_name = "$(hcl_string "$JFS_NAME")"

target_total_files = ${TARGET_TOTAL_FILES}
files_per_dir = ${FILES_PER_DIR}
test_threads = ${TEST_THREADS}
EOF

chmod 600 "$OUT_FILE"

echo "wrote ${OUT_FILE}"
echo "deploy_profile = ${DEPLOY_PROFILE}"
echo "allowed_ssh_cidrs = $(hcl_list "$ALLOWED_SSH_CIDRS_VALUE")"
echo "rustfs_secret_key = generated (${#RUSTFS_SECRET_KEY} chars)"
